---
label: deployment-tutorials
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: title
- type: field_group
  label: menu
  name: menu
  fields:
  - type: field_group
    name: docker
    label: docker
    fields:
    - type: text
      name: weight
      label: weight
pages:
- _articles/en/deploy/bitrise-app-deployment.md
- _articles/en/deploy/publish-your-app-to-appaloosa.md
- _articles/en/deploy/deploy-apps-to-deploygate-from-bitrise.md
- _articles/en/deploy/deploy-to-testfairy-with-bitrise.md
